### PR TITLE
chore: playbooks steps should not run after a step failure

### PR DESCRIPTION
**Pull request by yashmehrotra**
Fixes: #857

### CODE REVIEW

**Comment by adityathebe** [comment]
@moshloop Continuing playbook run on failure was intentional to support for the playbook filters. 

Example: Running a cleanup action or notify action after a previous action failed.

**Comment by moshloop** [comment]
@yashmehrotra - They should only run if we have an explicit filter e.g. `if: always()`

**Comment by yashmehrotra** [comment]
> They should only run if we have an explicit filter e.g. if: always()
@moshloop this is handled in the change

**Comment by adityathebe** [comment]
`if: always()` isn't the only case where we need to run after failure. eg: we also have `failure()`. And it's possible that the current action doesn't have those filters but maybe other actions down the line may have it.

If users want to **not** run actions after failure then they can use the `if: success()` filter. So I don't think we need to make any change in what we currently have.

If `if: success()` is a hassel, then we could add a new field to the playbook that's equivalent to `set -e` in shells.

**Comment by moshloop** [comment]
@adityathebe - I think we should default to the way Github does it, we can skip steps until we find one that will run - we don't need to break on failure

**Comment by yashmehrotra** [comment]
@moshloop @adityathebe 

For skipping playbook actions on failure, there can be cases when users have a filter and want to mix that with always(), like `filter: always() && config.class == "Pod"` so instead of checking and evaluating all, I am just returning the next action with filter and letting the filter function do the deciding

if the playbook has no action filters it will stop at failure

**Pull request merged**
