### PR TITLE
fix: slack labels in section limit

### PR DESCRIPTION
**Pull request by adityathebe**
resolves: https://github.com/flanksource/mission-control/issues/1329

image

### CODE REVIEW

**Comment by moshloop** [comment]
@adityathebe - Can we make sure that tags are always included, (and also sorted first?)

**Comment by adityathebe** [comment]
> @adityathebe - Can we make sure that tags are always included, (and also sorted first?)

@moshloop Isn't that already the case? All labels include the tags. We don't truncate any labels.

I've sorted the labels chronologically but I don't think we can place the tags before labels.
They're just key-vals. Unless the user calls 

```
slackSectionLabels(config.tags, config.labels)
```

but this wouldn't work well with other objects (checks, components) that don't have both tags/labels.

**Comment by moshloop** [comment]
@adityathebe we should just have a slackSectionLabels(config|component|check)

**Comment by adityathebe** [comment]
@moshloop  Made the change 

image

**Pull request merged**
